### ISSUE TITLE
AppCompat dependency?

### ISSUE THREAD

**Issue by fitsuli** [hrach/navigation-compose#20]
Hi! Thank you for sharing this library. I was looking through your code and stumbled upon the AppCompat dependency on :bottomsheet module that doesn't appear to be used anywhere.

Since the AppCompat itself is relatively heavy, I was wondering is there a reason for you to have it as dependency?

**Comment by hrach** [comment]
Thanks for pointing out. Yes, it seems we should remove it. Feel free to open PR or I'll fix it later.

**Comment by fitsuli** [comment]
> Thanks for pointing out. Yes, it seems we should remove it. Feel free to open PR or I'll fix it later.

Here's a PR: #21
